### ISSUE TITLE
Bug: Unexpected vibration after power button had been pressed

### ISSUE THREAD

**Issue by vasiliy-pdk** [42cc/p2psafety#11]
How to reproduce:
1. Start up the application
2. Hide the application ( press back button to see "desktop" )
3. Press power button to turn off display

Long vibration signal starts.

If you press power button to turn off display when application is showing vibration will not started.

If you wait for display turn off by timeout with hidden application you will get the vibration signal sometimes.

Problem does not disappears after you stop the application by some type of task manager. Only devise rebutting fix this problem.

Android 4.0.3
HTC EVO Design 4g

**Comment by vasiliy-pdk** [comment]
Sometimes unexpected vibration starts after some count of power button clicks. I am keeping the interval at least for 3 seconds before press power button next time

**Comment by alekzvik** [comment]
Ми це вже поправили, орієнтовно завтра на гугл плей

**Comment by vasiliy-pdk** [comment]
Поки здається гугл плей не оновився

**Comment by UncleVasya** [comment]
Василь, підтвердіть відсутність проблеми у новій версії.

**Comment by vasiliy-pdk** [comment]
Тепер здається зайвих вібрацій нема. Але виникла #34
