### ISSUE TITLE
event notification

### ISSUE THREAD

**Issue by alekzvik** [42cc/p2psafety#23]
Всім support-ерам надсилати notification через xmpp.
В ньому мають бути координати і короткий підсумок події?
Оформити це в вигляді окремої функції, щоб зараз це робилось по активації події, а в майбутньому вручну через карту диспетчера. Можна ввести перемикач в livesettings.

**Comment by myroslav** [comment]
Є варіант задіяти Server Sent Events - протокол базований на HTTP, і достатньо сумісний з всілякими proxy та accelerator-ами. Протокол є достатньо простий для реалізації як на сервері так і на клієнті, і існують бібліотеки, що його реалізують. Ще однією його перевага є в тому, що клієнтом SSE може виступати HTML5 аплікація (в нас поки таких клієнтів нема), де підтримка SSE є рідною.

**Comment by alekzvik** [comment]
done
