### ISSUE TITLE
event notification

### ISSUE THREAD

**Issue by alekzvik** [42cc/p2psafety#27]
Активісти мають приймати notification про івент через xmpp (деталі після виконання deps)
При отриманні - екран, на якому
- коротка інфа про подію,
- кнопка прийняти/ігнорувати
  Якщо юзер приймає, то іде відповідний запит за сервер

**Comment by vasiliy-pdk** [comment]
Ну і точка на карті - де це.

**Comment by mente** [comment]
Как вариант можно использовать [GCM](http://developer.android.com/google/gcm/index.html) для нотификаций и добавить actions на самой нотификации для быстрого реагирования.
Правда при этом придется хранить `registration_id` где-то на сервере либо держать сервис, который будет содержать в памяти список активных девайсов на текущий момент

**Comment by mente** [comment]
Да, гарантирования доставки нет. НО на практике сообщение доставляется как только девайс становится доступным в сети. А это происходит довольно часто (особенно при включенном экране).

Не знаю насчет XMPP протокола - он держит активное соединение? Если да, то это сожрет батарейку очень быстро. В тоже самое время GMS использует пуш сообщения и эффект на батарейку практически нулевой.

**Comment by mente** [comment]
Говоря про GMS я имел ввиду GCM :). 
Какие именно проблемы у вас вылазили? Несвоевременная доставка сообщений? Вроде если указать TTL=0, то сообщение получит наисвысший приоритет и сразу уже улетит на девайс (если девайс онлайн), иначе никогда не достигнет конечной точки.
Глупый вопрос: вы уверены, что registration_id корректен и обновлялся регулярно? :)

**Comment by UncleVasya** [comment]
Зробили через XMPP.
