### ISSUE TITLE
supporter screen 

### ISSUE THREAD

**Issue by alekzvik** [42cc/p2psafety#28]
Якщо активіст прийняв заклик на допомогу, то:
1. надсилається запит на сервер, який затверджує прийняття івенту.
2. активним стає екран активіста
Екран активіста, це:
2. коротке інфо про подію, ім’я, фото потерпілого
2. велика кнопка аудіозапису
2. велика кнопка відеозапису
2. активація аудіозапису потрійним нажаттям по кнопці блоку
2. в фоні раз на 5хв/500м надсилається оновлення координат

**Comment by vasiliy-pdk** [comment]
Ще раз нагадую, стеження за потерпілим має вестись постійно. І не просто точка а шлях пересування. Це дуже важливо. 

500 метрів - це дуже велика відстань для потерпілого. Тут рахунок йде на 10 ки метрів. 
За ним всі мають дуже пильно спостерігати як диспетчер, так і ті хто реагує на виклик.

Також само і для тих хто реагує. Їм треба буде оперативно бачити поточне місцеположення інших активістів, щоб зібратися в купу.

**Comment by alekzvik** [comment]
done
