### ISSUE TITLE
После 3х натискань на кнопку живлення йде вібрація але не працює тривога

### ISSUE THREAD

**Issue by vasiliy-pdk** [42cc/p2psafety#34]
По вібрації видно що реакція є. 3 натискання - вібрація декілька секунд але тривоги нема.
Не йде сповіщення, не розпочинається тривога.

Треба: 
Телефон у стані вимкненого дисплею, або у стані з активним дисплеєм ( заблокованим чи розблокованим )
1. Швидко натискаємо 3 рази на кнопку живлення
2. Відчуваємо вібрацію ( 1 секунду )
3. Бачимо у верхній панелі повідомлення що пішла тривога. У диспетчерській, на емейл, на телефон приходить сповіщення, відповідно до налаштувань

**Comment by alekzvik** [comment]
@akhavr?

**Comment by myroslav** [comment]
На скільки я знаю - треба ще 3 рази після вібрації натиснути.

On Sat, Feb 15, 2014 at 3:06 PM, Alex Vykalyuk notifications@github.comwrote:

> @akhavr https://github.com/akhavr?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/42cc/p2psafety/issues/34#issuecomment-35155728
> .

## 

....................................................................................................................................
Myroslav Opyr   ▪   CTO   ▪    Quintagroup   ▪   +1.917.475.4725   ▪
http://quintagroup.com
˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙

**Comment by vasiliy-pdk** [comment]
ага перевірив - працює. 3 рази - вібрація. Після вібрації ще три рази - тривога. 

Не занадто багато?

**Comment by alekzvik** [comment]
@vasiliy-pdk питання знято? тікет можна закривати?

**Comment by vasiliy-pdk** [comment]
Поки влаштує і так. Можна сзакривати
