### ISSUE TITLE
Can't login with facebook

### ISSUE THREAD

**Issue by vasiliy-pdk** [42cc/p2psafety#7]
Тыкаю войти с помощью профиля фейсбука. Вылазит pop-up с уточнением прав приложения, нажимаю "ок". Снова отображается кнопка "войти с фейсбук".

**Comment by alekzvik** [comment]
@vasiliy-pdk, please confirm that bug is fixed

**Comment by vasiliy-pdk** [comment]
Ok. Now I can use application. But log in by facebook asked when I click on the server addresses menu item in settings. Is it correct place? Then login process seems to be correct. 

But when I click logout button in settings this button does not hides after I logged out.

**Comment by alekzvik** [comment]
1. початкова проблема виправлена
2. #14 змінить спосіб реєстрації
